package net.olamaelcu.livtet.core.designsystem

/* GENERATED by packages/livtet-design-tokens — do not edit by hand.
 *
 * Lucide icon resource IDs, sourced from packages/livtet-design-tokens/tokens.json.
 * Each constant points at a vector drawable at R.drawable.lucide_<name>.
 *
 * Usage:
 *   Icon(
 *       painter = painterResource(LucideIcons.Book),
 *       contentDescription = "Book",
 *   )
 */
object LucideIcons {
    const val ArrowLeft: Int = R.drawable.lucide_arrow_left
    const val Info: Int = R.drawable.lucide_info
    const val Plus: Int = R.drawable.lucide_plus
    const val QrCode: Int = R.drawable.lucide_qr_code
    const val RefreshCw: Int = R.drawable.lucide_refresh_cw
    const val Search: Int = R.drawable.lucide_search
    const val Sparkles: Int = R.drawable.lucide_sparkles
    const val Trash2: Int = R.drawable.lucide_trash_2
}
