# vim: set ft=ruby :
platform :ios, '17.0'
use_frameworks!
inhibit_all_warnings!

# Minimal Podfile - pods removed for minimal build
target 'Livtet' do
  # No pods - using pure SwiftUI with FFI bridge
end

target 'LivtetUnitTests' do
  inherit! :search_paths
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '17.0'
      config.build_settings['ENABLE_USER_SCRIPT_SANDBOXING'] = 'YES'
      config.build_settings['SWIFT_VERSION'] = '5.10'
    end
  end
end
